
#pragma warning disable CS0169

namespace Sharp.UI.Internal
{
    class MauiSymbols
	{
        Microsoft.Maui.Controls.Binding binding;
        Microsoft.Maui.Controls.ElementTemplate elementTemplate;
        Microsoft.Maui.Controls.PropertyCondition propertyCondition;
        Microsoft.Maui.Controls.BindingCondition bindingCondition;

        Microsoft.Maui.Controls.VisualState visualState;

        // Count 126

        Microsoft.Maui.Controls.AbsoluteLayout absoluteLayout;
        Microsoft.Maui.Controls.ActivityIndicator activityIndicator;
        Microsoft.Maui.Controls.AdaptiveTrigger adaptiveTrigger;
        Microsoft.Maui.Controls.Application application;
        Microsoft.Maui.Controls.AppLinkEntry appLinkEntry;
        Microsoft.Maui.Controls.BackButtonBehavior backButtonBehavior;
        Microsoft.Maui.Controls.Border border;
        Microsoft.Maui.Controls.BoxView boxView;
        Microsoft.Maui.Controls.Button button;
        Microsoft.Maui.Controls.CarouselView carouselView;
        Microsoft.Maui.Controls.CheckBox checkBox;
        Microsoft.Maui.Controls.ClickGestureRecognizer clickGestureRecognizer;
        Microsoft.Maui.Controls.CollectionView collectionView;
        Microsoft.Maui.Controls.ColumnDefinition columnDefinition;
        Microsoft.Maui.Controls.CompareStateTrigger compareStateTrigger;
        Microsoft.Maui.Controls.ContentPage contentPage;
        Microsoft.Maui.Controls.ContentPresenter contentPresenter;
        Microsoft.Maui.Controls.DataTrigger dataTrigger;
        Microsoft.Maui.Controls.DatePicker datePicker;
        Microsoft.Maui.Controls.DeviceStateTrigger deviceStateTrigger;
        Microsoft.Maui.Controls.DragGestureRecognizer dragGestureRecognizer;
        Microsoft.Maui.Controls.DropGestureRecognizer dropGestureRecognizer;
        Microsoft.Maui.Controls.Editor editor;
        Microsoft.Maui.Controls.Entry entry;
        Microsoft.Maui.Controls.EntryCell entryCell;
        Microsoft.Maui.Controls.EventTrigger eventTrigger;
        Microsoft.Maui.Controls.FileImageSource fileImageSource;
        Microsoft.Maui.Controls.FlexLayout flexLayout;
        Microsoft.Maui.Controls.FlyoutItem flyoutItem;
        Microsoft.Maui.Controls.FlyoutPage flyoutPage;
        Microsoft.Maui.Controls.FontImageSource fontImageSource;
        Microsoft.Maui.Controls.FormattedString formattedString;
        Microsoft.Maui.Controls.Frame frame;
        Microsoft.Maui.Controls.GradientStop gradientStop;
        Microsoft.Maui.Controls.GraphicsView graphicsView;
        Microsoft.Maui.Controls.Grid grid;
        Microsoft.Maui.Controls.GridItemsLayout gridItemsLayout;
        Microsoft.Maui.Controls.HorizontalStackLayout horizontalStackLayout;
        Microsoft.Maui.Controls.HtmlWebViewSource htmlWebViewSource;
        Microsoft.Maui.Controls.Image image;
        Microsoft.Maui.Controls.ImageButton imageButton;
        Microsoft.Maui.Controls.ImageCell imageCell;
        Microsoft.Maui.Controls.IndicatorView indicatorView;
        Microsoft.Maui.Controls.Label label;
        Microsoft.Maui.Controls.LinearGradientBrush linearGradientBrush;
        Microsoft.Maui.Controls.LinearItemsLayout linearItemsLayout;
        Microsoft.Maui.Controls.ListView listView;
        Microsoft.Maui.Controls.MenuBar menuBar;
        Microsoft.Maui.Controls.MenuBarItem menuBarItem;
        Microsoft.Maui.Controls.MenuFlyout menuFlyout;
        Microsoft.Maui.Controls.MenuFlyoutSeparator menuFlyoutSeparator;
        Microsoft.Maui.Controls.MenuFlyoutSubItem menuFlyoutSubItem;
        Microsoft.Maui.Controls.MultiTrigger multiTrigger;
        Microsoft.Maui.Controls.NavigationPage navigationPage;
        Microsoft.Maui.Controls.OrientationStateTrigger orientationStateTrigger;
        Microsoft.Maui.Controls.PanGestureRecognizer panGestureRecognizer;
        Microsoft.Maui.Controls.Picker picker;
        Microsoft.Maui.Controls.PinchGestureRecognizer pinchGestureRecognizer;
        Microsoft.Maui.Controls.PointerGestureRecognizer pointerGestureRecognizer;
        Microsoft.Maui.Controls.ProgressBar progressBar;
        Microsoft.Maui.Controls.RadialGradientBrush radialGradientBrush;
        Microsoft.Maui.Controls.RadioButton radioButton;
        Microsoft.Maui.Controls.RefreshView refreshView;
        Microsoft.Maui.Controls.RowDefinition rowDefinition;
        Microsoft.Maui.Controls.ScrollView scrollView;
        Microsoft.Maui.Controls.SearchBar searchBar;
        Microsoft.Maui.Controls.SearchHandler searchHandler;
        Microsoft.Maui.Controls.Shadow shadow;
        Microsoft.Maui.Controls.Shell shell;
        Microsoft.Maui.Controls.Slider slider;
        Microsoft.Maui.Controls.SolidColorBrush solidColorBrush;
        Microsoft.Maui.Controls.Span span;
        Microsoft.Maui.Controls.StackLayout stackLayout;
        Microsoft.Maui.Controls.StateTrigger stateTrigger;
        Microsoft.Maui.Controls.Stepper stepper;
        Microsoft.Maui.Controls.StreamImageSource streamImageSource;
        Microsoft.Maui.Controls.SwipeGestureRecognizer swipeGestureRecognizer;
        Microsoft.Maui.Controls.SwipeItem swipeItem;
        Microsoft.Maui.Controls.SwipeItems swipeItems;
        Microsoft.Maui.Controls.SwipeItemView swipeItemView;
        Microsoft.Maui.Controls.SwipeView swipeView;
        Microsoft.Maui.Controls.Switch @switch;
        Microsoft.Maui.Controls.SwitchCell switchCell;
        Microsoft.Maui.Controls.Tab tab;
        Microsoft.Maui.Controls.TabBar tabBar;
        Microsoft.Maui.Controls.TabbedPage tabbedPage;
        Microsoft.Maui.Controls.TableRoot tableRoot;
        Microsoft.Maui.Controls.TableSection tableSection;
        Microsoft.Maui.Controls.TableView tableView;
        Microsoft.Maui.Controls.TapGestureRecognizer tapGestureRecognizer;
        Microsoft.Maui.Controls.TimePicker timePicker;
        Microsoft.Maui.Controls.ToolbarItem toolbarItem;
        Microsoft.Maui.Controls.Trigger trigger;
        Microsoft.Maui.Controls.UriImageSource uriImageSource;
        Microsoft.Maui.Controls.UrlWebViewSource urlWebViewSource;
        Microsoft.Maui.Controls.VerticalStackLayout verticalStackLayout;
        Microsoft.Maui.Controls.ViewCell viewCell;
        Microsoft.Maui.Controls.WebView webView;
        Microsoft.Maui.Controls.Window window;
        Microsoft.Maui.Controls.Shapes.ArcSegment shapes_arcSegment;
        Microsoft.Maui.Controls.Shapes.BezierSegment shapes_bezierSegment;
        Microsoft.Maui.Controls.Shapes.CompositeTransform shapes_compositeTransform;
        Microsoft.Maui.Controls.Shapes.Ellipse shapes_ellipse;
        Microsoft.Maui.Controls.Shapes.EllipseGeometry shapes_ellipseGeometry;
        Microsoft.Maui.Controls.Shapes.Line shapes_line;
        Microsoft.Maui.Controls.Shapes.LineGeometry shapes_lineGeometry;
        Microsoft.Maui.Controls.Shapes.LineSegment shapes_lineSegment;
        Microsoft.Maui.Controls.Shapes.MatrixTransform shapes_matrixTransform;
        Microsoft.Maui.Controls.Shapes.Path shapes_path;
        Microsoft.Maui.Controls.Shapes.PathFigure shapes_pathFigure;
        Microsoft.Maui.Controls.Shapes.PathGeometry shapes_pathGeometry;
        Microsoft.Maui.Controls.Shapes.PolyBezierSegment shapes_polyBezierSegment;
        Microsoft.Maui.Controls.Shapes.Polygon shapes_polygon;
        Microsoft.Maui.Controls.Shapes.Polyline shapes_polyline;
        Microsoft.Maui.Controls.Shapes.PolyLineSegment shapes_polyLineSegment;
        Microsoft.Maui.Controls.Shapes.PolyQuadraticBezierSegment shapes_polyQuadraticBezierSegment;
        Microsoft.Maui.Controls.Shapes.QuadraticBezierSegment shapes_quadraticBezierSegment;
        Microsoft.Maui.Controls.Shapes.Rectangle shapes_rectangle;
        Microsoft.Maui.Controls.Shapes.RectangleGeometry shapes_rectangleGeometry;
        Microsoft.Maui.Controls.Shapes.RotateTransform shapes_rotateTransform;
        Microsoft.Maui.Controls.Shapes.RoundRectangle shapes_roundRectangle;
        Microsoft.Maui.Controls.Shapes.RoundRectangleGeometry shapes_roundRectangleGeometry;
        Microsoft.Maui.Controls.Shapes.ScaleTransform shapes_scaleTransform;
        Microsoft.Maui.Controls.Shapes.SkewTransform shapes_skewTransform;
        Microsoft.Maui.Controls.Shapes.TransformGroup shapes_transformGroup;
        Microsoft.Maui.Controls.Shapes.TranslateTransform shapes_translateTransform;
    }
}

#pragma warning restore CS0169
