//
// MIT License
// Copyright Pawel Krzywdzinski
//
using Microsoft.CodeAnalysis;

namespace Sharp.UI.Generator.HotReload
{
    [Generator]
    public class Builder : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var assemblyName = context.CompilationProvider
                .Select(static (compilation, _) => compilation.AssemblyName);

            context.RegisterSourceOutput(assemblyName, static (spc, name) =>
            {
                if (name == "Sharp.UI")
                    return;

                spc.AddSource($"{name}.HotReload.g.cs", HotReloaderSource);
            });
        }

        const string HotReloaderSource = @"
//
// <auto-generated> Sharp.UI.Generator.HotReload.Builder
//

using System;
using System.Reflection.Metadata;

#if DEBUG

[assembly: MetadataUpdateHandlerAttribute(typeof(HotReloadHandler))]

internal static class HotReloadHandler
{
    internal static void ClearCache(Type[] updatedTypes)
    {
        Console.WriteLine(""ClearCache called"");
    }

    internal static void UpdateApplication(Type[] updatedTypes)
    {
        Console.WriteLine(""UpdateApplication called: "" +
            string.Join("", "", updatedTypes?.Select(t => t.FullName) ?? []));

        MainThread.BeginInvokeOnMainThread(() =>
            Sharp.UI.HotReloader.RebuildAll(updatedTypes));
    }

    internal static void BeforeUpdate(Type[] updatedTypes)
    {
        Console.WriteLine(""BeforeUpdate called"");
    }
}

#endif
";
    }
}