//
// MIT License
// Copyright Pawel Krzywdzinski
//

using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Sharp.UI.Generator.HotReload
{
    [Generator]
    public class Builder : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context) { }

        public void Execute(GeneratorExecutionContext context)
        {
            //Helpers.WaitForDebugger(context.CancellationToken);

            var assemblyName = context.Compilation.AssemblyName;

            if (assemblyName != "Sharp.UI")
            {
                context.AddSource($"{assemblyName}.HotReload.g.cs", hotReloader);
            }
        }

        string hotReloader = @"
//
// <auto-generated> Sharp.UI.Generator.HotReload.Builder
//

using System;
using System.Reflection.Metadata;

#if DEBUG
[assembly: MetadataUpdateHandlerAttribute(typeof(HotReloadHandler))]

internal static class HotReloadHandler
{
    internal static void ClearCache(Type[] updatedTypes)
    {
        Console.WriteLine(""ClearCache called"");
    }

    internal static void UpdateApplication(Type[] updatedTypes)
    {
        Console.WriteLine(""UpdateApplication called: "" +
            string.Join("", "", updatedTypes?.Select(t => t.FullName) ?? []));

        MainThread.BeginInvokeOnMainThread(() =>
            Sharp.UI.HotReloader.RebuildAll(updatedTypes));

    }

    internal static void BeforeUpdate(Type[] updatedTypes)
    {
        Console.WriteLine(""BeforeUpdate called"");
    }
}
#endif
";

    }
}
