//
// MIT License
// Copyright Pawel Krzywdzinski
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Sharp.UI.Generator.Classes
{
    /// <summary>
    /// Pure emitter: takes a ClassModel and produces text.
    /// No access to ISymbol / Compilation at all, which means this step
    /// does not have to run when the model has not changed.
    /// </summary>
    internal sealed class ClassGenerator
    {
        readonly ClassModel model;
        StringBuilder builder;
        bool generatedTopContentConstructor = false;

        public ClassGenerator(ClassModel model)
        {
            this.model = model;
        }

        // -----------------------------------------------------------------

        public void Build(SourceProductionContext context)
        {
            builder = new StringBuilder();

            builder.AppendLine("//");
            builder.AppendLine("// <auto-generated> Sharp.UI.Generator.Classes.Builder");
            builder.AppendLine("//");
            builder.AppendLine();
            builder.AppendLine("#nullable enable");
            builder.AppendLine();

            GenerateClassNamespace();

            builder.AppendLine();
            builder.AppendLine("#nullable restore");

            if (model.IsTopContentSymbol && !generatedTopContentConstructor && !model.IsSharpObject)
                return;

            context.AddSource($"{model.Namespace}.{model.FileName}.g.cs", builder.ToString());
        }

        string GetUsingString()
            => model.Namespace.Equals("Sharp.UI", StringComparison.Ordinal)
                ? "using Sharp.UI;\n\n"
                : "";

        void GenerateClassNamespace()
        {
            var sealedStr = model.IsSealed ? "sealed " : "";

            GenerateContainerUsingsIfNeeded();

            builder.Append($@"
namespace {model.Namespace}
{{
    {GetUsingString()}public {sealedStr}partial class {model.FullSymbolName}{BaseString()}
    {{");

            GenerateClassBody();

            builder.AppendLine($@"
    }}
}}");
        }

        // ------- container usings -------

        void GenerateContainerUsingsIfNeeded()
        {
            if (model.ContainerOfTypeName != null)
                builder.AppendLine(@"
using System.Collections;
using System.Collections.ObjectModel;
using System.Collections.Generic;
");
        }

        // ------- base string -------

        string BaseString()
        {
            if (model.ContainerOfTypeName != null)
                return model.IsSingleItemContainer
                    ? " : IEnumerable"
                    : $" : IList<{model.ContainerOfTypeName}>";

            return "";
        }

        void GenerateClassBody()
        {
            if (model.IsTopContentSymbol)
                GenerateNoParamTopContentConstructor();
            else
                GenerateConstructors();

            if (model.IsSharpObject)
            {
                GenerateSingleItemContainer();
                GenerateCollectionContainer();
                GenerateBindableProperties();
            }
        }

        // ---------------------------------
        // ----- single item container -----
        // ---------------------------------

        void GenerateSingleItemContainer()
        {
            if (model.ContainerOfTypeName == null || !model.IsSingleItemContainer)
                return;

            var newPrefix = model.IsNewPropertyContainer ? " new" : "";
            var argName = model.ContentPropertyName.ToLower();

            builder.AppendLine($@"
        // ----- single item container -----

        IEnumerator IEnumerable.GetEnumerator() {{ yield return this.{model.ContentPropertyName}; }}
        public{newPrefix} void Add({model.ContainerOfTypeName} {argName}) => this.{model.ContentPropertyName} = {argName};");
        }

        // --------------------------------
        // ----- collection container -----
        // --------------------------------

        void GenerateCollectionContainer()
        {
            if (model.ContainerOfTypeName == null || model.IsSingleItemContainer || model.IsAlreadyContainerOfThis)
                return;

            var prefix = $"this.{model.ContentPropertyName}";
            var type = model.ContainerOfTypeName;

            builder.AppendLine($@"
        // ----- collection container -----

        public int Count => {prefix}.Count;
        public {type} this[int index] {{ get => {prefix}[index]; set => {prefix}[index] = value; }}
        public bool IsReadOnly => false;
        public void Clear() => {prefix}.Clear();
        public bool Contains({type} item) => {prefix}.Contains(item);
        public void CopyTo({type}[] array, int arrayIndex) => {prefix}.CopyTo(array, arrayIndex);
        public IEnumerator<{type}> GetEnumerator() => {prefix}.GetEnumerator();
        public int IndexOf({type} item) => {prefix}.IndexOf(item);
        public void Insert(int index, {type} item) => {prefix}.Insert(index, item);
        public bool Remove({type} item) => {prefix}.Remove(item);
        public void RemoveAt(int index) => {prefix}.RemoveAt(index);
        IEnumerator IEnumerable.GetEnumerator() => {prefix}.GetEnumerator();
        public void Add({type} item) => {prefix}.Add(item);

        public void SetItems(params {type}[] items)
        {{
            this.Clear();
            foreach (var item in items) {{ this.Add(item); }}
        }}
");
        }

        // ------------------------
        // ----- constructors -----
        // ------------------------

        void GenerateNoParamTopContentConstructor()
        {
            // equivalent of: isImplicitlyDeclared && !isExplicitlyDeclared
            if (!model.HasImplicitParameterlessCtor || model.HasAnyExplicitPublicCtor)
                return;

            generatedTopContentConstructor = true;

            if (model.IsShell)
                builder.AppendLine($@"
        public new static {model.ClassName} Current => ({model.ClassName})Shell.Current;");

            builder.AppendLine($@"
        public {model.ClassName}()
        {{
            InitializeSharpUI();
        }}");
        }

        void GenerateNoParamConstructor()
        {
            builder.AppendLine($@"
        public {model.ClassName}() {{ }}");
        }

        void GenerateConstructors()
        {
            var camelCaseName = Helpers.CamelCase(model.ClassName);

            builder.AppendLine(@"
        // ----- constructors -----");

            var thisTail = ": this()";

            // this() constructor
            if (model.HasImplicitParameterlessCtor ||
                (model.BaseHasParameterlessCtor && !model.HasExplicitParameterlessCtor))
            {
                GenerateNoParamConstructor();
                thisTail = "";
            }

            if (model.HasImplicitParameterlessCtor ||
                model.HasExplicitParameterlessCtor ||
                (model.BaseHasParameterlessCtor && !model.HasExplicitParameterlessCtor))
            {
                BuildAdditionalConstructor(argsString: "", objectTail: "", thisTail: thisTail, camelCaseName: camelCaseName);
            }

            // this(...) constructors
            foreach (var ctor in model.Constructors)
            {
                var argsString = "";
                var baseArgsString = "";
                var argsList = new List<string>();

                foreach (var argument in ctor.Parameters)
                {
                    argsList.Add(argument.CamelCaseName);
                    argsString += $"{argument.TypeName} {argument.CamelCaseName}, ";

                    if (!string.IsNullOrEmpty(baseArgsString))
                        baseArgsString += ", ";
                    baseArgsString += argument.CamelCaseName;
                }

                var objectTail = argsList.Contains(camelCaseName, StringComparer.Ordinal) ? "Object" : "";

                BuildAdditionalConstructor(argsString, objectTail, $": this({baseArgsString})", camelCaseName);
            }
        }

        void BuildAdditionalConstructor(string argsString, string objectTail, string thisTail, string camelCaseName)
        {
            builder.AppendLine($@"
        public {model.ClassName}({argsString}out {model.FullSymbolName} {camelCaseName}{objectTail}) {thisTail}
        {{
            {camelCaseName}{objectTail} = this;
        }}");

            if (model.ContainerOfTypeName != null || model.IsAlreadyContainerOfThis)
                builder.AppendLine($@"
        public {model.ClassName}({argsString}System.Func<{model.ClassName}, {model.ClassName}> configure) {thisTail}
        {{
            configure(this);
        }}

        public {model.ClassName}({argsString}out {model.ClassName} {camelCaseName}, System.Func<{model.ClassName}, {model.ClassName}> configure) {thisTail}
        {{
            {camelCaseName} = this;
            configure(this);
        }}");
        }

        // --------------------------------------
        // ---- generate bindable properties ----
        // --------------------------------------

        void GenerateBindableProperties()
        {
            if (model.BindableProperties.Count == 0)
                return;

            builder.AppendLine(@"
        // ----- bindable properties -----");

            foreach (var property in model.BindableProperties)
                GeneratePropertyForField(property);
        }

        void GeneratePropertyForField(BindablePropertyModel property)
        {
            var name = property.Name;
            var typeName = property.TypeName;
            var newKeyword = property.IsNew ? " new" : "";

            var callbacksString = "";
            foreach (var callback in property.Callbacks)
                callbacksString += $@",
                {callback.Key}: {callback.Value}";

            var defaultValue = property.DefaultValueString != null
                ? $"({typeName}){property.DefaultValueString}"
                : $"default({typeName})";

            builder.Append($@"
        public static{newKeyword} readonly Microsoft.Maui.Controls.BindableProperty {name}Property =
            Microsoft.Maui.Controls.BindableProperty.Create(
                nameof({name}),
                typeof({typeName}),
                typeof({model.FullyQualifiedName}),
                {defaultValue}{callbacksString});

        public{newKeyword} {typeName} {name}
        {{
            get => ({typeName})GetValue({name}Property);
            set => SetValue({name}Property, value);
        }}
");
        }
    }
}
