//
// MIT License
// Copyright Pawel Krzywdzinski
//
using System.Text;
using Microsoft.CodeAnalysis;

namespace Sharp.UI.Generator.Extensions
{
    /// <summary>
    /// Pure emitter - takes an ExtensionModel and produces text.
    /// </summary>
    internal partial class ExtensionGenerator
    {
        readonly ExtensionModel model;
        StringBuilder builder;

        public ExtensionGenerator(ExtensionModel model)
        {
            this.model = model;
        }

        // -----------------------------------------------------------------

        public void Build(SourceProductionContext context)
        {
            if (!model.HasContent)
                return;

            builder = new StringBuilder();

            builder.AppendLine("//");
            builder.AppendLine("// <auto-generated> Sharp.UI.Generator.Extensions.Builder");
            builder.AppendLine("//");
            builder.AppendLine();
            builder.AppendLine("#nullable enable");
            builder.AppendLine("#pragma warning disable CS8601");
            builder.AppendLine();

            GenerateExtensionNameSpace();

            builder.AppendLine();
            builder.AppendLine("#pragma warning restore CS8601");
            builder.AppendLine("#nullable restore");

            context.AddSource(model.HintName, builder.ToString());
        }

        string GetUsingString() => model.IncludeSharpUIUsing ? "using Sharp.UI;\n" : "";

        void GenerateExtensionNameSpace()
        {
            builder.Append($@"
namespace {model.TargetNamespace}
{{
    using Sharp.UI.Internal;
    {GetUsingString()}
    public static partial class {model.ExtensionClassName}
    {{");

            foreach (var property in model.Properties)
                GeneratePropertyMethods(property);

            foreach (var @event in model.Events)
                GenerateEventMethods(@event);

            if (model.EmitITextAlignment)
                GenerateExtensionMethods_ITextAlignment();

            foreach (var property in model.InterfaceProperties)
                GeneratePropertyMethods(property);

            builder.AppendLine($@"
    }}
}}");
        }

        // -----------------------------------------------------------------
        // dispatcher - all decisions were already made in ExtensionModelBuilder
        // -----------------------------------------------------------------

        void GeneratePropertyMethods(PropertyModel p)
        {
            if (p.EmitValue) GenerateExtensionMethod_Value(p);
            if (p.EmitThickness) GenerateExtensionMethods_Thickness(p);
            if (p.EmitList) GenerateExtensionMethod_List(p, p.ListElementTypeName);
            if (p.EmitBindablePropertyBuilder) GenerateExtensionMethod_BindablePropertyBuilder(p);
            if (p.EmitSetters) GenerateExtensionMethod_Setters(p);
            if (p.EmitSettersThickness) GenerateExtensionMethod_Setters_Thickness(p);
            if (p.EmitSettersBuilder) GenerateExtensionMethod_SettersBuilder(p);
            if (p.EmitDataTemplate) GenerateExtensionMethod_DataTemplate(p);
            if (p.EmitGetValue) GenerateExtensionMethod_GetValue(p);
            if (p.AnimateTransformName != null) GenerateExtensionMethod_AnimateTo(p, p.AnimateTransformName);
        }

        // -----------------------------------
        // ----- value -----
        // -----------------------------------

        void GenerateExtensionMethod_Value(PropertyModel p)
        {
            if (model.IsSealed)
                builder.Append($@"
        public static {model.SymbolTypeName} {p.PropertyName}(this {model.SymbolTypeName} self,
            {p.PropertyTypeName} {p.CamelCaseName})
        {{
            {p.ValueAssignment}
            return self;
        }}
");
            else
                builder.Append($@"
        public static T {p.PropertyName}<T>(this T self,
            {p.PropertyTypeName} {p.CamelCaseName})
            where T : {model.SymbolTypeName}
        {{
            {p.ValueAssignment}
            return self;
        }}
");
        }

        // -----------------------------------
        // ----- thickness (Margin/Padding) -----
        // -----------------------------------

        void GenerateExtensionMethods_Thickness(PropertyModel p)
        {
            var bindable = $"{model.SymbolTypeName}.{p.PropertyName}Property";

            if (model.IsSealed)
                builder.Append($@"
        public static {model.SymbolTypeName} {p.PropertyName}(this {model.SymbolTypeName} self, double horizontalSize, double verticalSize)
        {{
            self.SetValue({bindable}, new Thickness(horizontalSize, verticalSize));
            return self;
        }}

        public static {model.SymbolTypeName} {p.PropertyName}(this {model.SymbolTypeName} self, double left, double top, double right, double bottom)
        {{
            self.SetValue({bindable}, new Thickness(left, top, right, bottom));
            return self;
        }}

#nullable disable
        public static {model.SymbolTypeName} {p.PropertyName}(this {model.SymbolTypeName} self, object _ = null, double left = 0, double top = 0, double right = 0, double bottom = 0)
        {{
            self.SetValue({bindable}, new Thickness(left, top, right, bottom));
            return self;
        }}
#nullable enable
");
            else
                builder.Append($@"
        public static T {p.PropertyName}<T>(this T self, double horizontalSize, double verticalSize)
            where T : {model.SymbolTypeName}
        {{
            self.SetValue({bindable}, new Thickness(horizontalSize, verticalSize));
            return self;
        }}

        public static T {p.PropertyName}<T>(this T self, double left, double top, double right, double bottom)
            where T : {model.SymbolTypeName}
        {{
            self.SetValue({bindable}, new Thickness(left, top, right, bottom));
            return self;
        }}

#nullable disable
        public static T {p.PropertyName}<T>(this T self, object _ = null, double left = 0, double top = 0, double right = 0, double bottom = 0)
            where T : {model.SymbolTypeName}
        {{
            self.SetValue({bindable}, new Thickness(left, top, right, bottom));
            return self;
        }}
#nullable enable
");
        }

        // -----------------------------------
        // ----- setters -----
        // -----------------------------------

        void GenerateExtensionMethod_Setters(PropertyModel p)
        {
            if (model.IsSealed)
                builder.Append($@"
        public static SettersContext<{model.SymbolTypeName}> {p.PropertyName}(this SettersContext<{model.SymbolTypeName}> self,
            {p.PropertyTypeName} {p.CamelCaseName})
        {{
            self.XamlSetters.Add(new Setter {{ Property = {p.BindablePropertyName}, Value = {p.CamelCaseName} }});
            return self;
        }}
");
            else
                builder.Append($@"
        public static SettersContext<T> {p.PropertyName}<T>(this SettersContext<T> self,
            {p.PropertyTypeName} {p.CamelCaseName})
            where T : {model.SymbolTypeName}
        {{
            self.XamlSetters.Add(new Setter {{ Property = {p.BindablePropertyName}, Value = {p.CamelCaseName} }});
            return self;
        }}
");
        }

        void GenerateExtensionMethod_Setters_Thickness(PropertyModel p)
        {
            if (model.IsSealed)
                builder.Append($@"
        public static SettersContext<{model.SymbolTypeName}> {p.PropertyName}(this SettersContext<{model.SymbolTypeName}> self, double horizontalSize, double verticalSize)
        {{
            self.XamlSetters.Add(new Setter {{ Property = {p.BindablePropertyName}, Value = new Thickness(horizontalSize, verticalSize) }});
            return self;
        }}

        public static SettersContext<{model.SymbolTypeName}> {p.PropertyName}(this SettersContext<{model.SymbolTypeName}> self, double left, double top, double right, double bottom)
        {{
            self.XamlSetters.Add(new Setter {{ Property = {p.BindablePropertyName}, Value = new Thickness(left, top, right, bottom) }});
            return self;
        }}

#nullable disable
        public static SettersContext<{model.SymbolTypeName}> {p.PropertyName}(this SettersContext<{model.SymbolTypeName}> self, object _ = default, double left = 0, double top = 0, double right = 0, double bottom = 0)
        {{
            self.XamlSetters.Add(new Setter {{ Property = {p.BindablePropertyName}, Value = new Thickness(left, top, right, bottom) }});
            return self;
        }}
#nullable enable
");
            else
                builder.Append($@"
        public static SettersContext<T> {p.PropertyName}<T>(this SettersContext<T> self, double horizontalSize, double verticalSize)
            where T : {model.SymbolTypeName}
        {{
            self.XamlSetters.Add(new Setter {{ Property = {p.BindablePropertyName}, Value = new Thickness(horizontalSize, verticalSize) }});
            return self;
        }}

        public static SettersContext<T> {p.PropertyName}<T>(this SettersContext<T> self, double left, double top, double right, double bottom)
            where T : {model.SymbolTypeName}
        {{
            self.XamlSetters.Add(new Setter {{ Property = {p.BindablePropertyName}, Value = new Thickness(left, top, right, bottom) }});
            return self;
        }}

#nullable disable
        public static SettersContext<T> {p.PropertyName}<T>(this SettersContext<T> self, object _ = default, double left = 0, double top = 0, double right = 0, double bottom = 0)
            where T : {model.SymbolTypeName}
        {{
            self.XamlSetters.Add(new Setter {{ Property = {p.BindablePropertyName}, Value = new Thickness(left, top, right, bottom) }});
            return self;
        }}
#nullable enable
");
        }

        // -----------------------------------
        // ----- get value (attached) -----
        // -----------------------------------

        void GenerateExtensionMethod_GetValue(PropertyModel p)
        {
            if (model.IsSealed)
                builder.Append($@"
        public static {p.PropertyTypeName} Get{p.PropertyName}Value<T>(this {model.SymbolTypeName} self)
        {{
            return ({p.PropertyTypeName})self.GetValue({p.BindablePropertyName});
        }}
");
            else
                builder.Append($@"
        public static {p.PropertyTypeName} Get{p.PropertyName}Value<T>(this T self)
            where T : {model.SymbolTypeName}
        {{
            return ({p.PropertyTypeName})self.GetValue({p.BindablePropertyName});
        }}
");
        }

        // -----------------------------------
        // ----- animate to -----
        // -----------------------------------

        void GenerateExtensionMethod_AnimateTo(PropertyModel p, string transformationName)
        {
            if (model.IsSealed)
                builder.Append($@"
        public static Task<bool> Animate{p.PropertyName}To(this {model.SymbolTypeName} self, {p.PropertyTypeName} value, uint length = 250, Easing? easing = null)");
            else
                builder.Append($@"
        public static Task<bool> Animate{p.PropertyName}To<T>(this T self, {p.PropertyTypeName} value, uint length = 250, Easing? easing = null)
            where T : {model.SymbolTypeName}");

            builder.Append($@"
        {{
            {p.PropertyTypeName} fromValue = self.{p.PropertyName};
            var transform = (double t) => Transformations.{transformationName}(fromValue, value, t);
            var callback = ({p.PropertyTypeName} actValue) => {{ self.{p.PropertyName} = actValue; }};
            return Transformations.AnimateAsync<{p.PropertyTypeName}>(self, ""Animate{p.PropertyName}To"", transform, callback, length, easing);
        }}
");
        }

        // -----------------------------------
        // ----- binding builders -----
        // -----------------------------------

        void GenerateExtensionMethod_BindablePropertyBuilder(PropertyModel p)
        {
            if (model.IsSealed)
                builder.Append($@"
        public static {model.SymbolTypeName} {p.PropertyName}(this {model.SymbolTypeName} self, Func<PropertyContext<{p.PropertyTypeName}>, IPropertyBuilder<{p.PropertyTypeName}>> configure)
        {{
            var context = new PropertyContext<{p.PropertyTypeName}>(self, {p.BindablePropertyName});
            configure(context).Build();
            return self;
        }}
");
            else
                builder.Append($@"
        public static T {p.PropertyName}<T>(this T self, Func<PropertyContext<{p.PropertyTypeName}>, IPropertyBuilder<{p.PropertyTypeName}>> configure)
            where T : {model.SymbolTypeName}
        {{
            var context = new PropertyContext<{p.PropertyTypeName}>(self, {p.BindablePropertyName});
            configure(context).Build();
            return self;
        }}
");
        }

        void GenerateExtensionMethod_SettersBuilder(PropertyModel p)
        {
            if (model.IsSealed)
                builder.Append($@"
        public static SettersContext<{model.SymbolTypeName}> {p.PropertyName}(this SettersContext<{model.SymbolTypeName}> self, Func<PropertySettersContext<{p.PropertyTypeName}>, IPropertySettersBuilder<{p.PropertyTypeName}>> configure)
        {{
            var context = new PropertySettersContext<{p.PropertyTypeName}>(self.XamlSetters, {p.BindablePropertyName});
            configure(context).Build();
            return self;
        }}
");
            else
                builder.Append($@"
        public static SettersContext<T> {p.PropertyName}<T>(this SettersContext<T> self, Func<PropertySettersContext<{p.PropertyTypeName}>, IPropertySettersBuilder<{p.PropertyTypeName}>> configure)
            where T : {model.SymbolTypeName}
        {{
            var context = new PropertySettersContext<{p.PropertyTypeName}>(self.XamlSetters, {p.BindablePropertyName});
            configure(context).Build();
            return self;
        }}
");
        }

        // -----------------------------------
        // ----- data template -----
        // -----------------------------------

        void GenerateExtensionMethod_DataTemplate(PropertyModel p)
        {
            if (model.IsSealed)
                builder.Append($@"
        public static {model.SymbolTypeName} {p.PropertyName}<T>(this {model.SymbolTypeName} self, System.Func<object> loadTemplate)
        {{
            {p.DataTemplateAssignment}
            return self;
        }}
");
            else
                builder.Append($@"
        public static T {p.PropertyName}<T>(this T self, System.Func<object> loadTemplate)
            where T : {model.SymbolTypeName}
        {{
            {p.DataTemplateAssignment}
            return self;
        }}
");
        }

        // -----------------------------------
        // ----- list -----
        // -----------------------------------

        void GenerateExtensionMethod_List(PropertyModel p, string elementTypeName)
        {
            var tail = p.PropertyTypeName.EndsWith("?") ? "?" : "";

            if (model.IsSealed)
                builder.Append($@"
        public static {model.SymbolTypeName} {p.PropertyName}(this {model.SymbolTypeName} self,
            IList<{elementTypeName}> {p.CamelCaseName})
        {{
            foreach (var item in {p.CamelCaseName})
                {p.AccessedWith}.{p.PropertyName}{tail}.Add(item);
            return self;
        }}

        public static {model.SymbolTypeName} {p.PropertyName}(this {model.SymbolTypeName} self,
            params {elementTypeName}[] {p.CamelCaseName})
        {{
            foreach (var item in {p.CamelCaseName})
                {p.AccessedWith}.{p.PropertyName}{tail}.Add(item);
            return self;
        }}
");
            else
                builder.Append($@"
        public static T {p.PropertyName}<T>(this T self,
            IList<{elementTypeName}> {p.CamelCaseName})
            where T : {model.SymbolTypeName}
        {{
            foreach (var item in {p.CamelCaseName})
                {p.AccessedWith}.{p.PropertyName}{tail}.Add(item);
            return self;
        }}

        public static T {p.PropertyName}<T>(this T self,
            params {elementTypeName}[] {p.CamelCaseName})
            where T : {model.SymbolTypeName}
        {{
            foreach (var item in {p.CamelCaseName})
                {p.AccessedWith}.{p.PropertyName}{tail}.Add(item);
            return self;
        }}
");
        }

        // -----------------------------------
        // ----- events -----
        // -----------------------------------

        void GenerateEventMethods(EventModel e)
        {
            if (model.IsSealed)
            {
                builder.Append($@"
        public static {model.SymbolTypeName} On{e.Name}(this {model.SymbolTypeName} self, {e.HandlerTypeName} handler)
        {{
            self.{e.Name} += handler;
            return self;
        }}
");
                builder.Append($@"
        public static {model.SymbolTypeName} On{e.Name}(this {model.SymbolTypeName} self, System.Action<{model.SymbolTypeName}> action)
        {{
            self.{e.Name} += (o, arg) => action(self);
            return self;
        }}
");
            }
            else
            {
                builder.Append($@"
        public static T On{e.Name}<T>(this T self, {e.HandlerTypeName} handler)
            where T : {model.SymbolTypeName}
        {{
            self.{e.Name} += handler;
            return self;
        }}
");
                builder.Append($@"
        public static T On{e.Name}<T>(this T self, System.Action<T> action)
            where T : {model.SymbolTypeName}
        {{
            self.{e.Name} += (o, arg) => action(self);
            return self;
        }}
");
            }
        }
    }
}
